### ISSUE TITLE
Visualization not working on Linux/Wayland

### ISSUE THREAD

**Issue by lavaux** [DESI-UR/VAST#72]
Running `example_scripts/visualize_voids_VoidFinder.py` on linux/wayland triggers an error in PyOpenGL and PyOpenGLTK.

I have not reported that issue to PyOpenGLTK yet. However I would suggest to include a word of warning in the documentation/readme about compatibility issues.

Here is the stacktrace:
```
Traceback (most recent call last):
  File "/home/guilhem/Software/VAST/example_scripts/visualize_voids_VoidFinder.py", line 76, in <module>
    viz = VoidRender(holes_xyz=holes_xyz, 
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vast-1.1.1-py3.9-linux-x86_64.egg/vast/voidfinder/viz/void_render.py", line 551, in __init__
    app.Canvas.__init__(self, 
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vispy/app/canvas.py", line 173, in __init__
    self._app = use_app(call_reuse=False)
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vispy/app/application.py", line 47, in __init__
    self._use(backend_name)
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vispy/app/application.py", line 233, in _use
    __import__(mod_name, globals(), level=1)
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/vispy/app/backends/_tk.py", line 29, in <module>
    import pyopengltk
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/pyopengltk/__init__.py", line 28, in <module>
    from pyopengltk.linux import OpenGLFrame
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/pyopengltk/linux.py", line 8, in <module>
    from OpenGL import GL, GLX
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/OpenGL/GLX/__init__.py", line 3, in <module>
    from OpenGL.GLX.VERSION.GLX_1_0 import *
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/OpenGL/GLX/VERSION/GLX_1_0.py", line 14, in <module>
    from OpenGL.raw.GLX.VERSION.GLX_1_0 import *
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/OpenGL/raw/GLX/VERSION/GLX_1_0.py", line 44, in <module>
    def glXChooseVisual(dpy,screen,attribList):pass
  File "/home/guilhem/venv/vast/lib64/python3.9/site-packages/OpenGL/raw/GLX/VERSION/GLX_1_0.py", line 13, in _f
    return _p.createFunction( function,_p.PLATFORM.GLX,'GLX_VERSION_GLX_1_0',error_checker=_errors._error_checker)
AttributeError: 'EGLPlatform' object has no attribute 'GLX'
```

**Comment by QuiteAFoxtrot** [comment]
Have you encountered this issue when not using the Wayland backend?  I could be a bit out of date but isn't Wayland still considered a somewhat experimental choice of graphical server?  I don't see any harm in pointing this out in the docs though.

**Comment by lavaux** [comment]
Sorry I did not reply to this. But indeed no, this problem does not occur on X backend and I did not try on Windows or OSX. Wayland is not experimental anymore for ~2 years minimum. Actually this is the recommended backend for past version of Ubuntu and it will be the default for Ubuntu 22.04 including for NVIDIA.

Some references:
* https://discourse.ubuntu.com/t/trying-wayland-by-default-again/20575
* https://www.omgubuntu.co.uk/2021/01/ubuntu-21-04-will-use-wayland-by-default
* https://wiki.ubuntu.com/Wayland
* https://ubuntu.com/blog/ubuntu-17-10-releases-with-gnome-kubernetes-1-8-minimal-base-images:
> The new default desktop features the latest version of GNOME with extensions developed in collaboration with the GNOME Shell team to provide a familiar experience to long-standing Ubuntu users. 17.10 will run Wayland as the default display server on compatible hardware, with the option of Xorg where required.

**Comment by QuiteAFoxtrot** [comment]
Ok thanks @lavaux I think we'll need to take a bit of a deeper look at this

**Comment by QuiteAFoxtrot** [comment]
Had a chance to do some testing - indeed this visualization does not work on Wayland, but I am marking this issue Closed because I cannot get anything else to work on Wayland either, even a simple script like:
```import numpy
import matplotlib.pyplot as plt
data = numpy.arange(10)
plt.plot(data, data)
plt.show()``` 
fails with libGL errors.  I believe this is a Wayland problem, not a VAST issue, but we will update our docs to reflect this known problem.

**Comment by QuiteAFoxtrot** [comment]
Sorry - realized it would be more accurate to re-open this and mark it as Docs instead of bugs then we'll close when we link in a PR for this docs update.
